### ISSUE TITLE
Initial Release

### ISSUE THREAD

**Issue by AdmiringWorm** [WormieCorp/Cake.Transifex#1] opened 2017-03-16 19:24 UTC
Initial realse of the transifex cake addin which adds support for `status`, `push` and `pull`.

**Comment by gep13** [comment] 2017-03-17 08:59
:+1:

**Comment by gep13** [comment] 2017-03-17 08:59
@AdmiringWorm as a side note, you might want to make the `develop` branch the default branch.

**Comment by AdmiringWorm** [comment] 2017-03-17 15:32
@gep13 not with my work flow, if I set the develop branch as the default issues would close when a commit/PR is merged to the develop branch.
IMO issues should stay open until they have been provided in the a stable build.

**Comment by gep13** [comment] 2017-03-17 15:51
Interesting... hadn't thought of it that way.

The main reason that I do it is so that PR's from external contributors come into the correct branch.  9 times out of 10, they use the default branch, without thinking.

**Comment by AdmiringWorm** [comment] 2017-03-17 16:01
> The main reason that I do it is so that PR's from external contributors come into the correct branch. 9 times out of 10, they use the default branch, without thinking.

While that is certainly a problem, I've never had that many PR's on my projects so it's never been I problem for me. Only once that I can remember, in that case I just re-targeted the PR to the develop branch, and asked the submitter to rebase/merge it towards the develop branch.

**Comment by gep13** [comment] 2017-03-17 17:52
We (Cake) have had a few issues with it in the past, but I totally understand your point of view as well.  Going to have to mull this one over a bit 😄

**Comment by AdmiringWorm** [comment] 2017-03-17 17:55
👍 
I'll probably set the develop branch as default if it ever becomes a problem in the future.
BTW, do you know if there is possible for the gitreleasemanager to create a changelog based on issues that are pending closure? (don't know if the github api supports this or not).

/cc @gep13

**Comment by gep13** [comment] 2017-03-17 18:07
GitReleaseManager is based off of the fact that issues have been:

* Labeled with one, and only one, of the configured labels
* Is assigned to a milestone
* The issue is closed

That is not to say that these things won't change in the future, but that is how it currently works.

**Comment by AdmiringWorm** [comment] 2017-03-17 18:15
yeah, I thought that was the how it worked. Just wanted to make sure, just in case I was missing something.

**Comment by gep13** [comment] 2017-03-17 18:15
Happy to take any input on how it can be done different.  That project is somewhat neglected.  Need to get back to it at some point.

**Comment by AdmiringWorm** [comment] 2017-03-17 18:20
Unfortunately I don't know if it is even possible to get a pending closure state (couldn't find any in the api documents).

I'll probably open a issue on GitReleaseManager sometime in the future detailing my views on some changes.

**Comment by gep13** [comment] 2017-03-17 19:01
>@AdmiringWorm said...
Unfortunately I don't know if it is even possible to get a pending closure state (couldn't find any in the api documents).

Likely not.  Would likely need to be an additional label to provide an indication of current state.  i.e `Done`

>@AdmiringWorm said...
I'll probably open a issue on GitReleaseManager sometime in the future detailing my views on some changes.

Sounds good to me.

**Closed** 2017-03-21 12:09 UTC
Labels: enhancement

**Comment by gep13** [comment] 2017-03-21 14:20
@AdmiringWorm great work on getting this released 👍

**Comment by AdmiringWorm** [comment] 2017-03-21 14:21
@gep13 thanks, had to skip a few corners when trying to build it on osx and linux though. (tooling issues)

**Comment by gep13** [comment] 2017-03-21 14:26
@AdmiringWorm baby steps 😄 

So, you doing a PR to the ChocolateyGUI repo next? 😛

**Comment by AdmiringWorm** [comment] 2017-03-21 14:35
> So, you doing a PR to the ChocolateyGUI repo next? 😛

while I could do that, there would still be some steps that needs to be done before I can.
Most notably the creation of the project on transifex.

There probably should also be some kind of discussion on whether the translated sources should be checked in or not and if everything should be automated on appveyor or not.

**Comment by AdmiringWorm** [comment] 2017-03-21 14:37
in the meantime I've updated the [Hello Transifex](https://github.com/AdmiringWorm/Hello-Transifex) demo project.
